/**
 * Generates robots.txt and sitemap.xml into dist/ after a build.
 *
 * The route list is read from `dist/route-meta.json`, which vite.config emits
 * from `shared/routes.ts` — the same table the prerender step and the pages
 * themselves use. A page that exists but is missing from the sitemap is worse
 * than no sitemap at all, so this deliberately has no route list of its own.
 *
 *   node scripts/generate-sitemap.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const dist = path.join(root, 'dist');

const SITE_URL = (process.env.SITE_URL ?? 'https://northforgestudio.vercel.app').replace(/\/$/, '');

const metaPath = path.join(dist, 'route-meta.json');
if (!fs.existsSync(metaPath)) {
  console.error('✗ dist/route-meta.json is missing — run `vite build` before the sitemap step.');
  process.exit(1);
}

const { routes } = JSON.parse(fs.readFileSync(metaPath, 'utf8'));
const indexable = routes.filter((route) => route.index);

const escapeXml = (value) =>
  value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

/*
 * No <lastmod>.
 *
 * It used to be `new Date()`, so every deploy told Google that all seven pages
 * had just changed. Google ignores a lastmod it learns not to trust, which
 * quietly removes the one hint that says "this page is actually fresh". A
 * correct value means per-page content dates, which this build does not track,
 * so omitting it is more honest than lying on every deploy.
 */
const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs — do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${indexable
  .map(
    (route) => `  <url>
    <loc>${escapeXml(`${SITE_URL}${route.path === '/' ? '/' : route.path}`)}</loc>${
      route.changefreq ? `\n    <changefreq>${route.changefreq}</changefreq>` : ''
    }${route.priority ? `\n    <priority>${route.priority}</priority>` : ''}
  </url>`,
  )
  .join('\n')}
</urlset>
`;

/*
 * The authenticated areas are disallowed because there is nothing to index
 * behind them — not as a security control, since every one of them requires a
 * session and enforces it with RLS. The noindex screens (/login, /register,
 * /mfa) are deliberately NOT disallowed: a disallowed URL cannot be crawled,
 * so its `noindex` tag would never be read.
 */
const robots = `# Generated by scripts/generate-sitemap.mjs — do not edit by hand.
User-agent: *
Allow: /
Disallow: /app
Disallow: /portal

Sitemap: ${SITE_URL}/sitemap.xml
`;

fs.mkdirSync(dist, { recursive: true });
fs.writeFileSync(path.join(dist, 'sitemap.xml'), sitemap);
fs.writeFileSync(path.join(dist, 'robots.txt'), robots);

console.log(`✓ dist/sitemap.xml (${indexable.length} urls) · dist/robots.txt · SITE_URL=${SITE_URL}`);
