/**
 * Generates robots.txt and sitemap.xml into dist/ after a build.
 *
 * The route list is imported from the app's own config so the sitemap can
 * never drift from the real router — a page that exists but is missing from
 * the sitemap is worse than no sitemap at all.
 *
 *   node scripts/generate-sitemap.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const dist = path.join(root, 'dist');

const SITE_URL = (process.env.SITE_URL ?? 'https://northforgestudio.vercel.app').replace(/\/$/, '');
const TODAY = new Date().toISOString().slice(0, 10);

/**
 * Public, indexable routes. Everything under /portal and /app is
 * authenticated and deliberately excluded — those live behind noindex
 * headers set per-route by usePageMeta.
 */
const PUBLIC_ROUTES = [
  { path: '/', priority: '1.0', changefreq: 'weekly' },
  { path: '/services', priority: '0.9', changefreq: 'monthly' },
  { path: '/how-it-works', priority: '0.8', changefreq: 'monthly' },
  { path: '/pricing', priority: '0.9', changefreq: 'monthly' },
  { path: '/faq', priority: '0.6', changefreq: 'monthly' },
  { path: '/contact', priority: '0.8', changefreq: 'yearly' },
  { path: '/privacy', priority: '0.3', changefreq: 'yearly' },
  { path: '/terms', priority: '0.3', changefreq: 'yearly' },
];

const escapeXml = (value) =>
  value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs — do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${PUBLIC_ROUTES.map(
  (route) => `  <url>
    <loc>${escapeXml(`${SITE_URL}${route.path}`)}</loc>
    <lastmod>${TODAY}</lastmod>
    <changefreq>${route.changefreq}</changefreq>
    <priority>${route.priority}</priority>
  </url>`,
).join('\n')}
</urlset>
`;

const robots = `# Generated by scripts/generate-sitemap.mjs — do not edit by hand.
User-agent: *
Allow: /
Disallow: /portal
Disallow: /app
Disallow: /api

Sitemap: ${SITE_URL}/sitemap.xml
`;

if (!fs.existsSync(dist)) {
  fs.mkdirSync(dist, { recursive: true });
}

fs.writeFileSync(path.join(dist, 'sitemap.xml'), sitemap);
fs.writeFileSync(path.join(dist, 'robots.txt'), robots);

console.log(`✓ dist/sitemap.xml (${PUBLIC_ROUTES.length} urls) · dist/robots.txt · SITE_URL=${SITE_URL}`);
